### ISSUE TITLE
Org not found when call "/tyk/org/keys/1"

### ISSUE THREAD

**Issue by tonywangcn** [TykTechnologies/tyk-pro-docker-demo#26]
Hi, admin

First of all thanks for making such demo for newbie like me. Very resourceful.

I'm trying to make it up. Just changed the tyk.conf a little bit without a valid license key.

"use_db_app_configs" is changed to "false" to use the gateway api.

As I did the follow steps the error msg "Org not found" shows up:

1. Create api with "/tyk/apis"

```
{
    "name": "Test API 11111",
    "slug": "test-api-1111",
    "api_id": "2114",
    "org_id": "1",
    "auth": {
      "auth_header_name": "Authorization"
    },
    "proxy": {
      "listen_path": "/test-api-1/",
      "target_url": "http://httpbin.org/",
      "strip_listen_path": true
    },
    "active": true
}
```
It did create a api file in ./test_apps/ path of container 'tyk-pro-docker-demo_tyk-dashboard_1'

2.  Call "/tyk/reload" to reload the service
3.  Add new Org key by call "/tyk/org/keys/1", the same org_id as 1.

Body

```
{
  "quota_max": 60,
  "quota_renews": 1406121006,
  "quota_renewal_rate": 60,
  "allowance": 100,
  "rate": 100,
  "per": 5,
  "org_id": "1"
}

```

Response shows it's added successfully.

```
{
    "key": "1",
    "status": "ok",
    "action": "added"
}
```
4. When I call "/tyk/org/keys/1" with the org_id created above, the error msg "Org not found".  With "/tyk/org/keys/" to query all created org_ids, it returns empty array.

Query by org_id
```
{
    "status": "error",
    "message": "Org not found"
}
```
Query all org_id
```
{
    "keys": []
}
```

So, what's the problem? Is there anything I did wrong, and how to fix it. Thanks!

**Comment by asoorm** [comment]
The tyk pro docker demo is a demo configuration for the enterprise stack. There are probably far too many configuration changes you will need to change it into a Community Edition configuration. For example - The community edition has no concept of "organisations", no dashboard & with this pro-edition, you would normally talk to the Dashboard APIs, rather than the Gateway API directly.

I would recommend you take a look at the following resources to help you on your way:

https://hub.docker.com/r/tykio/tyk-gateway
https://www.youtube.com/watch?v=YFU2HLeT0HY
https://www.youtube.com/watch?v=9f4ct-VKNxY

Good luck, have fun - Closing this issue.

**Comment by tonywangcn** [comment]
Thanks for your reply. It would be great if you put it down in the Gateway API docs, https://github.com/TykTechnologies/tyk/blob/master/swagger.yml. I thought it's a bug or misconfiguration somewhere and spent lots of time working on it.
